/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://wha77ltzf5hhdgl7wv33qzrwqq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-eqcddn644jf6jevf5eiylt7ybq",
    "aws_cognito_identity_pool_id": "us-east-1:a77ce48a-1044-4cb8-b4b4-9558ac79fd9b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_eLjQlelDg",
    "aws_user_pools_web_client_id": "4mtifs5ki1nr0mhd7caamit80n",
    "oauth": {}
};


export default awsmobile;
