/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_cognito_identity_pool_id:
    'us-east-1:8a7eeb18-d2cd-40d7-9391-efea9827e8d8',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_5hhx2ml3Y',
  aws_user_pools_web_client_id: '4uskosas5ugvcig217juv54296',
  oauth: {},
  aws_appsync_graphqlEndpoint:
    'https://zsp2qa7vkbbtdkkvvbti6v7bu4.appsync-api.us-east-1.amazonaws.com/graphql',
  aws_appsync_region: 'us-east-1',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
  aws_appsync_apiKey: 'da2-7l5atgftsncvvcuwkfrseui23m',
  aws_user_files_s3_bucket: 'devresources02755-dev',
  aws_user_files_s3_bucket_region: 'us-east-1'
}
export default awsmobile
